FROM python:3.7

WORKDIR /usr/src/app

ADD ./requirements.txt ./

RUN apt update && apt install -y zip

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt install -y ./google-chrome-stable_current_amd64.deb && \
    wget https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip -d /root/

RUN pip install --no-cache-dir -r requirements.txt

ADD . .
